services:
  banner-service:
    build:
      context: .
      dockerfile: cmd/banner_service/Dockerfile
    image: avito-assignment
    container_name: banner-service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: postgres:16-alpine
    container_name: banner-service-database
    environment:
      POSTGRES_DB: banner-service-database
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: banner-service-redis
    volumes:
      - ./redis_data:/data